# Generated by Django 3.2.2 on 2022-05-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_name_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='name_value',
        ),
        migrations.AddField(
            model_name='name',
            name='hora',
            field=models.CharField(default='Some String', max_length=255),
        ),
        migrations.AddField(
            model_name='name',
            name='nome_value',
            field=models.CharField(default='Some String', max_length=250),
        ),
    ]
