# Generated by Django 3.2.2 on 2022-05-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220528_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='nome_value',
        ),
        migrations.AddField(
            model_name='name',
            name='name_value',
            field=models.CharField(default='Some String', max_length=100),
        ),
    ]
